### ISSUE TITLE
Adding Header Image & Category

### ISSUE THREAD

**Issue by Am4rokTV** [Monster2408/DiscordWebhook#1]
Hey, I really love your plugin ! 
If it's possible, could you add the "header image" in the message embed ? And maybe the possibility to add the categories with "%category%" too ? 

It's not a priority, just a little suggestion to make your plugin a bit better. 

Thx a lot for this plugin ❤️

**Comment by hashimotok-delien** [comment]
I'm very sorry for the delay, but I've added two new features.
The header image is not yet compatible with plugins such as FIFU.
[https://wordpress.org/plugins/webhook-discord/](https://wordpress.org/plugins/webhook-discord/)
