### ISSUE TITLE
%category% return Array instead of categories 

### ISSUE THREAD

**Issue by barnabehvrd** [Monster2408/DiscordWebhook#2]
As I said in the title, `%category%` return `Array` instead of the catogrie(s)

![image](https://user-images.githubusercontent.com/40314287/165530562-dcb55d50-1cf9-41c4-a5f9-6c3f52a99ef3.png)
![image](https://user-images.githubusercontent.com/40314287/165530709-c9e31044-996e-4290-9af5-c07241b27683.png)

**Comment by hashimotok-delien** [comment]
遅くなりましたが不具合を修正しました
Google Translate > Sorry for the delay, but I fixed the problem

Webhook for Discord v1.2.2
https://wordpress.org/plugins/webhook-discord/
